### ISSUE TITLE
Update bot to use his own state storage until March 31

### ISSUE THREAD

**Issue by pryabov** [Scheduler-Bot/scheduler-bot#18]
Due this post:
https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/

Should be implemented support for own bot state storage (it can be sql database hosted in the cloud). This point need to be discussed and investigated

**Comment by akravch** [comment]
I am not completely sure it applies to the scheduler-bot. There is a comment from a guy under the article you've mentioned clarifying who should bother about it:

> Who --> Those who created bots with "bot services" menu option (no longer available) and have one service for the entire bot.

We need to double-check that, but I guess at the time we had deployed the bot, it had used the latest available option.

Also, I don't see any of the classes nor methods mentioned in the article - nothing related to the state storage really. Maybe it used to be true earlier, before the latest framework version.

**Comment by pryabov** [comment]
@akravch agree with you will investigate

**Comment by akravch** [comment]
@pryabov I guess we can close it since we've missed March 31 anyway :D

**Comment by pryabov** [comment]
@akravch agree 👍
