### ISSUE TITLE
Bug: Authorization issue trying to send a message

### ISSUE THREAD

**Issue by akravch** [Scheduler-Bot/scheduler-bot#7]
Sometimes the bot crashes with HTTP 401 trying to send a message to the conversation, however it can reply to user messages without any issues.

The crash happens in `ScheduledMessageProcessorService.SendMessageAsync`.

**Comment by pryabov** [comment]
@akravch looks like this is related issue https://github.com/Microsoft/BotBuilder/issues/2737

**Comment by pryabov** [comment]
Fixed with commit: https://github.com/Scheduler-Bot/scheduler-bot/commit/ae2c31271387c5dd22eee2df02ab125f682456e7
